"""task_state_modifying

Revision ID: 1638ebb88673
Revises: 150361dbf02d
Create Date: 2022-11-12 17:50:14.660741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1638ebb88673'
down_revision = '150361dbf02d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
