"""dateime_task_added

Revision ID: c300f840f0e2
Revises: 1638ebb88673
Create Date: 2022-11-12 17:53:07.213413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c300f840f0e2'
down_revision = '1638ebb88673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expiration_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'expiration_time')
    # ### end Alembic commands ###
